[licenses]
allow = []
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "ffprog", version = "*" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident", version = "*" },
]
